import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ProviderComponent } from "@/Contexts/UserContext";

import UserStateNavElement from "@/Components/UserStateNavElement";
import Dashboard from "./dashboard/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProviderComponent>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <nav style={{display:"flex", justifyContent: "space-evenly"}}>
            <Link href="/">Hominv</Link>
            {/* normally user page links would be hidden if not logged in, but I'm leaving dashboard exposed for now for testing purposes */}
            <Link href={"/dashboard"}>Dashboard</Link>
            <Link href={'/inventory'}>Inventory</Link>
            <div>
              <UserStateNavElement></UserStateNavElement>
            </div>
          </nav>
          {children}
        </body>
      </ProviderComponent>
    </html>
  );
}
