import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { ProviderComponent } from "@/Contexts/UserContext";

import UserStateNavElement from "@/Components/UserStateNavElement";
import Image from "next/image";
import ApplicationLinks from "@/Components/ApplicationLinks";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import Notafucation from "@/Components/Notafucation";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./Theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProviderComponent>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased  min-h-screen`}>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <header style={{display:"flex", justifyContent: "space-between", alignItems: "center"}}>
                <Link href="/"><Image className="mainLogo" loading="eager" src="/HomeInventory.svg" width="80" height={80} alt="Hi Logo"></Image></Link>
                <ApplicationLinks></ApplicationLinks>
                <UserStateNavElement></UserStateNavElement>
              </header>
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
          <Notafucation></Notafucation>
        </body>
      </ProviderComponent>
    </html>
  );
}
